<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		
		<script type="text/javascript">
		/*
		概念：
			Promise是异步编程的一种解决方案。那什么时候我们会来处理异步事件呢?
			一种很常见的场景应该就是网络请求了。
			我们封装一个网络请求的函数，因为不能立即拿到结果，所以不能像简单的3+4=7一样将结果返回。
			所以往往我们会传入另外一个函数，在数据请求成功时，将数据通过传入的函数回调出去。
			如果只是一个简单的网络请求，那么这种方案不会给我们带来很大的麻烦。
			但是，当网络请求非常复杂时，就会出现回调地狱。
		*/
	 
	 /*使用：链式编程
		参数=>函数=>必要参数resolve, reject=>resolve, reject本身也是函数。
		在 new 的时候，Promise颞部构造函数会执行两个操作：保存一些状态信息；执行传入的参数
		在执行传入的回调函数时，会传入两个参数，resolve；reject（他们本身又是函数）
		Promise的优雅之处就在于，对于异步请求的操作，他不会将请求代码和处理代码同时放在一起
			而是将请求代码和处理代码进行分离。在请求代码中调用resolve，然后调用Promise的then(下一步)方法进行数据的处理。
		下面的示例中的 data 参数只是模拟了参数的传递，因为setTimeout没有参数...
		在resolve函数中的参数会自动的传递到 then 中
		*请求成功之后才会回调then方法，请求失败之后会跳过then方法直接进入到catch方法对请求错误或者失败的信息进行处理操作
	 */
	// 模拟异步请求操作
		new Promise((resolve, reject) => {
			// 第一次异步请求
			setTimeout((data) => {
				resolve(data);  // 成功的时候调用该方法
				reject('第一次请求失败'); // 请求失败之后回调该方法，对失败的数据处理会跳过then方法，进入到catch方法进行处理
			}, 2000)
		}).then((data) => {
			// 第一次请求数据处理
			console.log('勒!');
			return new Promise((resolve, reject) => {
				
				// 第二次异步请求
				setTimeout((data) => {
					resolve(data);
					reject('第二次请求失败');
				}, 2000)
			}).then((data) => {
				// 第二次请求数据处理
				console.log('里昂!');
				return new Promise((resolve, reject) => {
					
					// 第三次异步请求
					setTimeout((data) => {
						resolve(data);
						reject('第三次请求失败');
					}, 2000)
				}).then((data) => {
					// 第三次请求处理
					console.log('梁!');
				}).catch((data) => {
					// 第三次请求失败处理
					console.log(data);
				})
			}).catch((data) => {
				// 第二次请求失败处理
				console.log(data);
			})
		}).catch((data) => {
			// 第一次请求失败的处理
			console.log(data);
		})
		</script>
	</body>
</html>
